name: front-Pipline

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: chouchenechadha/front-session15
  SERVICE_NAME: front-app
  PATH_VPS: /home/user/frontend

jobs:

  Unit_test:
    runs-on: ubuntu-latestt
    steps:
      - name: Clone repo
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm i

      - name: run unit test
        run: npm run test


  sonarqube-code-quality-scan-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: run code quality test
        run: npm run lint


  build-and-push:
    runs-on: ubuntu-latest
    needs: [Unit_test, sonarqube-code-quality-scan-job]
    steps:

      - name: Clone repo
        uses: actions/checkout@v6

      - name: build docker image
        run: docker build -t ${{ env.DOCKER_IMAGE }} .

      - name: tag docker image
        run: docker tag ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_IMAGE }}:v${{ github.run_number }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push versioned image
        run: docker push ${{ env.DOCKER_IMAGE }}:v${{ github.run_number }}

      - name: push latest image
        run: docker push ${{ env.DOCKER_IMAGE }}


  deployment:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: cnct via ssh and deplyment
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ${{ env.PATH_VPS }}
            sudo docker compose down ${{ env.SERVICE_NAME }}
            sudo docker compose pull ${{ env.SERVICE_NAME }}
            sudo docker compose up -d --force-recreate
